# Site Settings
title: "Jung Han Shin"
author: "Jung Han Shin"
email: "cautiousjh@snu.ac.kr"
description: "A cognitive neuroscientist bridging human cognition and artificial intelligence."
url: "https://cautiousjh.github.io"
baseurl: ""

# Theme Settings
remote_theme: niklasbuschmann/contrast

# Theme Config
show_excerpts: true   
katex: true          
DateFormat: "%B %d, %Y"

# Navigation (Header)
header_pages:
  - index.html
  - cv.md

# Build Settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Exclude (Clean up)
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - README.md
